# Generated by Django 5.0.6 on 2024-07-31 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aniuniverse', '0002_mangas'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('U', 'Unwatched'), ('W', 'Watching'), ('C', 'Completed'), ('OH', 'On Hold'), ('D', 'Dropped'), ('PW', 'Plan to Watch')], default='U', max_length=13)),
                ('episodes', models.IntegerField()),
                ('score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('animes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aniuniverse.animes')),
            ],
        ),
        migrations.CreateModel(
            name='MangaUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('U', 'Unread'), ('R', 'Reading'), ('C', 'Completed'), ('OH', 'On Hold'), ('D', 'Dropped'), ('PR', 'Plan to Read')], default='U', max_length=12)),
                ('chapters', models.IntegerField()),
                ('score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('mangas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aniuniverse.mangas')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animeList', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aniuniverse.animeuser')),
                ('favorite_anime', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aniuniverse.animes')),
                ('favorite_manga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aniuniverse.mangas')),
                ('mangaList', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aniuniverse.mangauser')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
