# Generated by Django 5.0.6 on 2024-08-13 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aniuniverse', '0004_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='favorite_anime',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='favorite_manga',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favorite_anime',
            field=models.ManyToManyField(blank=True, to='aniuniverse.animes'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favorite_manga',
            field=models.ManyToManyField(blank=True, to='aniuniverse.mangas'),
        ),
    ]
