# Generated by Django 5.0.6 on 2024-08-13 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aniuniverse', '0005_remove_userprofile_favorite_anime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mail',
            field=models.EmailField(default=None, max_length=255),
        ),
    ]
