# Generated by Django 5.0.6 on 2024-08-13 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aniuniverse', '0006_user_mail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='animeList',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='mangaList',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='animeList',
            field=models.ManyToManyField(blank=True, to='aniuniverse.animeuser'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mangaList',
            field=models.ManyToManyField(blank=True, to='aniuniverse.mangauser'),
        ),
    ]
