# Generated by Django 5.0.6 on 2024-08-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aniuniverse', '0007_remove_userprofile_animelist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animeuser',
            name='score',
            field=models.IntegerField(),
        ),
    ]
