# Generated by Django 5.0.6 on 2024-08-14 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aniuniverse', '0008_alter_animeuser_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mangauser',
            name='score',
            field=models.IntegerField(),
        ),
    ]
