# Generated by Django 5.0.6 on 2024-08-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aniuniverse', '0009_alter_mangauser_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profilePicture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
