# Generated by Django 5.0.6 on 2024-08-19 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aniuniverse', '0010_userprofile_profilepicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mail',
            field=models.EmailField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
