# Generated by Django 5.0.6 on 2024-08-19 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aniuniverse', '0011_alter_user_mail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profilePicture',
        ),
        migrations.AddField(
            model_name='user',
            name='profilePicture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
